<style>
#crm-leads-page{--ui-purple:#6d35e8;--ui-ink:#111827;--ui-muted:#7c8ba1;--ui-line:#e8edf4;background:#f7f8fc;color:var(--ui-ink);padding:18px;border-radius:18px;min-height:calc(100vh - 72px)}
#crm-leads-page .crm-page-header{display:flex;align-items:center;padding:6px 4px 18px;margin-bottom:16px;border-bottom:1px solid #e7ebf2}
#crm-leads-page .crm-page-header__title{font-size:24px!important;line-height:1.2!important;font-weight:760!important;letter-spacing:-.035em;color:#111827;margin-bottom:5px}
#crm-leads-page .crm-page-header__subtitle{font-size:13px;color:#7b879b;margin:0}#crm-leads-page .crm-breadcrumb{display:none}
#crm-leads-page .crm-page-header>div:last-child{gap:9px!important}
#crm-leads-page .crm-page-header .btn{min-height:42px;padding:9px 15px!important;border:1px solid #dfe5ee!important;border-radius:11px!important;background:#fff!important;color:#25344b!important;font-size:13px;font-weight:700;box-shadow:0 2px 6px rgba(31,42,68,.035)!important;transition:.17s ease}
#crm-leads-page .crm-page-header .btn:hover{border-color:#cbd4e2!important;background:#f9fafc!important;transform:translateY(-1px)}
#crm-leads-page .crm-page-header .btn-primary-600{background:linear-gradient(135deg,#7c3aed,#6930df)!important;border-color:#7136e8!important;color:#fff!important;box-shadow:0 7px 16px rgba(109,53,232,.24)!important}
#crm-leads-page .crm-page-header .btn-primary-600:hover{background:#5823ce!important;color:#fff!important}

#crm-leads-page>.row{--bs-gutter-x:12px;--bs-gutter-y:12px;margin-bottom:18px!important}
#crm-leads-page .crm-stat-card{min-height:104px;border:1px solid #e5eaf2;border-radius:14px;background:#fff;box-shadow:0 2px 8px rgba(31,42,68,.035)}
#crm-leads-page .crm-stat-card:hover{transform:translateY(-2px);border-color:#d8deea;box-shadow:0 8px 22px rgba(31,42,68,.075)}
#crm-leads-page .crm-stat-card__glow{display:none}#crm-leads-page .crm-stat-card__body{padding:16px}#crm-leads-page .crm-stat-card__icon{width:38px;height:38px;border-radius:50%;font-size:18px}
#crm-leads-page .crm-stat-card__label{font-size:10px;font-weight:750;letter-spacing:.065em;color:#77869b}#crm-leads-page .crm-stat-card__value{font-size:21px;font-weight:760;color:#131c2c}#crm-leads-page .crm-stat-card__footer{margin-top:8px;padding-top:8px}

#crm-leads-page .crm-lead-segments{padding:0;margin-bottom:14px!important}#crm-leads-page .crm-lead-segments__head{margin:0 0 9px;padding:0 3px}
#crm-leads-page .crm-lead-segments__title{font-size:11px;font-weight:750;letter-spacing:.07em;color:#78879b}#crm-leads-page .crm-lead-segments__hint{font-size:11px;color:#9aa6b8}
#crm-leads-page .crm-lead-segments__track{gap:8px;padding:1px 2px 5px}#crm-leads-page .crm-segment-card{min-width:145px;max-width:190px;padding:9px 11px;border:1px solid #e2e7ef;border-radius:11px;background:#fff;box-shadow:0 2px 6px rgba(31,42,68,.025)}
#crm-leads-page .crm-segment-card__icon{width:32px;height:32px;border-radius:50%;font-size:15px;background:#f0edff;color:#6d35e8}#crm-leads-page .crm-segment-card__name{font-size:11px;color:#4e5e75}#crm-leads-page .crm-segment-card__counts strong{font-size:14px;color:#172033}
#crm-leads-page .crm-segment-card.is-active{border-color:#cfc2fb;background:#f5f2ff;box-shadow:0 0 0 2px rgba(109,53,232,.07)}#crm-leads-page .crm-segment-card.is-active .crm-segment-card__icon{background:#6d35e8;color:#fff}#crm-leads-page .crm-segment-card.is-active .crm-segment-card__name,#crm-leads-page .crm-segment-card.is-active .crm-segment-card__counts strong{color:#4c20aa}

#crm-leads-page .crm-filter-bar{padding:12px;margin-bottom:12px!important;border:1px solid #e1e6ef;border-radius:14px;background:#fff;box-shadow:0 3px 10px rgba(31,42,68,.035)}
#crm-leads-page .crm-filter-bar__grid{display:grid;grid-template-columns:minmax(220px,1.55fr) repeat(7,minmax(120px,1fr));gap:8px}#crm-leads-page .crm-filter-field label{display:none}
#crm-leads-page .crm-filter-field .form-control,#crm-leads-page .crm-filter-field .form-select{height:42px;border:1px solid #e0e5ed;border-radius:10px!important;background-color:#fff;color:#26344a;font-size:12px;box-shadow:none}
#crm-leads-page .crm-filter-field .form-control::placeholder{color:#9aa6b8}#crm-leads-page .crm-filter-field .form-control:focus,#crm-leads-page .crm-filter-field .form-select:focus{border-color:#8b65ed;box-shadow:0 0 0 3px rgba(109,53,232,.1)}
#crm-leads-page .crm-filter-actions{margin-top:9px!important;gap:8px}#crm-leads-page .crm-filter-actions .btn{min-height:38px;padding:7px 14px!important;border-radius:9px!important;font-size:12px;font-weight:700}
#crm-leads-page .crm-filter-actions .btn-primary-600{background:#f2efff;border:1px solid #ddd3fb;color:#5b2bc1;box-shadow:none}#crm-leads-page .crm-filter-actions .btn-primary-600:hover{background:#e9e3ff}#crm-leads-page .crm-filter-actions .btn-outline-neutral-500{background:#fff;border-color:#e2e7ef;color:#718096}

#crm-leads-page>.d-flex.justify-content-end{margin:0 0 9px!important;align-items:center;gap:8px}#crm-leads-page>.d-flex.justify-content-end::before{content:"View";font-size:11px;font-weight:700;color:#929db0}
#crm-leads-page .crm-view-toggle{padding:3px;border:1px solid #e1e6ee;border-radius:10px;background:#fff;box-shadow:0 2px 6px rgba(31,42,68,.03)}
#crm-leads-page .crm-view-toggle button{width:auto;min-width:70px;height:32px;padding:0 10px;border-radius:7px;background:transparent;display:inline-flex;align-items:center;justify-content:center;gap:6px;font-size:11px;font-weight:700;color:#8190a5}
#crm-leads-page .crm-view-toggle button[data-view="list"]::after{content:"List"}#crm-leads-page .crm-view-toggle button[data-view="grid"]::after{content:"Cards"}#crm-leads-page .crm-view-toggle button.is-active{background:#f0ecff;color:#6130cc;box-shadow:none}

#crm-leads-page .crm-list-only{border:1px solid #e2e7ef!important;border-radius:15px!important;background:#fff;box-shadow:0 5px 18px rgba(31,42,68,.055)!important;overflow:hidden}
#crm-leads-page .crm-list-only .table-responsive{border-radius:14px;scrollbar-width:thin;scrollbar-color:#c7cfdb #f4f6f9}#crm-leads-page .crm-list-only .table{min-width:1100px;margin:0;border-collapse:separate;border-spacing:0;color:#1d293d}
#crm-leads-page .crm-list-only thead th{padding:14px 15px;border:0;border-bottom:1px solid #e7ebf2;background:#fafbfc;color:#657389;font-size:9.5px;font-weight:760;letter-spacing:.075em;text-transform:uppercase;white-space:nowrap}
#crm-leads-page .crm-list-only tbody td{height:68px;padding:11px 15px;border:0;border-bottom:1px solid #edf0f5;background:#fff;vertical-align:middle;transition:background .14s ease}#crm-leads-page .crm-list-only tbody tr:last-child td{border-bottom:0}#crm-leads-page .crm-list-only tbody tr:hover td{background:#f8faff!important}
#crm-leads-page .crm-list-only th:first-child,#crm-leads-page .crm-list-only td:first-child{position:sticky;left:0;z-index:3;min-width:210px;background:#fff;box-shadow:8px 0 15px -16px rgba(22,33,52,.55)}#crm-leads-page .crm-list-only thead th:first-child{z-index:5;background:#fafbfc}
#crm-leads-page .crm-list-only th:last-child,#crm-leads-page .crm-list-only td:last-child{position:sticky;right:0;z-index:3;min-width:126px;background:#fff;box-shadow:-8px 0 15px -16px rgba(22,33,52,.55)}#crm-leads-page .crm-list-only thead th:last-child{z-index:5;background:#fafbfc}
#crm-leads-page .crm-list-only tbody tr:hover td:first-child,#crm-leads-page .crm-list-only tbody tr:hover td:last-child{background:#f8faff!important}
#crm-leads-page .crm-lead-name{font-size:13px;font-weight:740;color:#111827;letter-spacing:-.01em}#crm-leads-page .crm-lead-meta{margin-top:2px;font-size:11px;color:#8491a5}
#crm-leads-page .crm-lead-identity{display:flex;align-items:center;gap:10px;min-width:0}#crm-leads-page .crm-lead-avatar{width:32px;height:32px;flex:0 0 32px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,#7c5cff,#536dfe);color:#fff;font-size:10px;font-weight:800;box-shadow:0 3px 8px rgba(83,83,220,.18)}#crm-leads-page .crm-lead-identity__text{min-width:0}
#crm-leads-page .crm-category-badge{margin-top:4px;padding:2px 7px;border:0;background:#f0edff;color:#6941c6;font-size:10px}#crm-leads-page .badge{border-radius:999px!important;border:0!important;background:#f3f6fa!important;color:#58687f!important;font-size:10.5px!important;font-weight:650!important;box-shadow:none!important}
#crm-leads-page .crm-inline-trigger{height:30px;min-height:30px;min-width:112px;padding:3px 9px;border:0!important;background:var(--crm-tone-bg);font-size:11px;font-weight:680;box-shadow:none}#crm-leads-page .crm-inline-control--owner .crm-inline-trigger{min-width:128px}#crm-leads-page .crm-inline-trigger:focus,#crm-leads-page .crm-inline-control.is-open .crm-inline-trigger{box-shadow:0 0 0 3px var(--crm-tone-ring)}
#crm-leads-page .crm-inline-menu{padding:6px;border:1px solid #e2e7ef;border-radius:11px;box-shadow:0 14px 34px rgba(31,42,68,.14)}#crm-leads-page .crm-inline-option{padding:8px 9px;font-size:11px}#crm-leads-page .crm-followup-badge{border:0;min-height:29px;padding:4px 10px;font-size:11px;box-shadow:none}
#crm-leads-page .fc-table-actions{gap:3px}#crm-leads-page .fc-table-actions .btn{width:30px;height:30px;min-width:30px;padding:0!important;border:0!important;border-radius:8px!important;background:transparent!important;box-shadow:none!important}#crm-leads-page .fc-table-actions .btn:hover{background:#f0edff!important;transform:none}

#crm-leads-page .crm-card-grid{gap:12px}#crm-leads-page .crm-record-card{padding:17px;border:1px solid #e4e8f0;border-radius:14px;background:#fff;box-shadow:0 3px 12px rgba(31,42,68,.045)}#crm-leads-page .crm-record-card:hover{transform:translateY(-2px);border-color:#d8d0f5;box-shadow:0 9px 22px rgba(31,42,68,.08)}
#crm-leads-page #crm-save-filter-form{margin:12px 0 18px!important;border:1px dashed #dce2eb!important;border-radius:12px!important;background:#fafbfc!important;box-shadow:none!important}#crm-leads-page #crm-save-filter-form .card-body{min-height:56px;padding:9px 11px!important;gap:8px!important}#crm-leads-page #crm-save-filter-form label{margin:0 8px 0 0!important;white-space:nowrap;color:#7a879a;font-size:11px!important;font-weight:650}
#crm-leads-page #crm-save-filter-form .form-control{height:38px;border:1px solid #e1e6ee;border-radius:9px!important;background:#fff;font-size:12px;box-shadow:none}#crm-leads-page #crm-save-filter-form .form-control:focus{border-color:#8b65ed;box-shadow:0 0 0 3px rgba(109,53,232,.09)}#crm-leads-page #crm-save-filter-form .btn{height:38px;padding:7px 14px!important;border-radius:9px!important;background:#fff;color:#5d2cc7;border:1px solid #d9cff7;font-size:12px;font-weight:700;white-space:nowrap}#crm-leads-page #crm-save-filter-form .btn:hover{background:#f1edff}#crm-leads-page nav[role="navigation"]{margin-top:14px}

@media(max-width:1399px){#crm-leads-page .crm-filter-bar__grid{grid-template-columns:repeat(4,minmax(150px,1fr))}}
@media(max-width:1199px){#crm-leads-page .crm-page-header{align-items:flex-start;flex-direction:column}#crm-leads-page .crm-page-header>div:last-child{width:100%}#crm-leads-page .crm-page-header .btn{flex:1 1 auto}}
@media(max-width:767px){#crm-leads-page{padding:12px;border-radius:13px}#crm-leads-page .crm-page-header>div:last-child{display:grid!important;grid-template-columns:1fr 1fr}#crm-leads-page .crm-page-header .btn{padding-inline:9px!important}#crm-leads-page .crm-filter-bar__grid{grid-template-columns:1fr 1fr}#crm-leads-page>.d-flex.justify-content-end::before{display:none}#crm-leads-page .crm-view-toggle{width:100%}#crm-leads-page .crm-view-toggle button{flex:1}#crm-leads-page #crm-save-filter-form .card-body{display:grid!important;grid-template-columns:1fr}#crm-leads-page #crm-save-filter-form label{margin:0!important}#crm-leads-page #crm-save-filter-form .btn{width:100%}}
@media(max-width:480px){#crm-leads-page .crm-filter-bar__grid{grid-template-columns:1fr}}
</style>
