<?php

return [

    'defaults' => [
        'packages' => ['Standard enrollment', 'Sibling discount'],
        'campuses' => ['Main campus'],
        'year_groups' => ['Year 7', 'Year 8', 'Year 9', 'Year 10'],
        'subjects' => ['English', 'Mathematics', 'Science', 'Arabic'],
        'nationalities' => ['British', 'American', 'Pakistani', 'Indian'],
        'genders' => ['Male', 'Female', 'Other'],
        'relationships' => ['Mother', 'Father', 'Guardian', 'Other'],
        'languages' => ['English', 'Arabic', 'Urdu'],
        'payment_countries' => ['United Kingdom', 'United States', 'United Arab Emirates'],
        'enrollment_dates' => [],
    ],

    'types' => [
        'packages' => [
            'label' => 'Packages',
            'icon' => 'solar:box-linear',
            'group' => 'programs',
            'model' => \App\Models\StudentPackage::class,
            'permission' => 'package',
            'field' => 'name',
            'status' => true,
        ],
        'campuses' => [
            'label' => 'Campuses',
            'icon' => 'solar:buildings-2-linear',
            'group' => 'programs',
            'model' => \App\Models\School::class,
            'permission' => 'school',
            'field' => 'name',
            'status' => true,
        ],
        'year_groups' => [
            'label' => 'Year groups',
            'icon' => 'solar:calendar-mark-linear',
            'group' => 'programs',
            'model' => \App\Models\StudentYear::class,
            'permission' => 'year',
            'field' => 'name',
            'status' => true,
            'requires_group' => true,
        ],
        'subjects' => [
            'label' => 'Subjects',
            'icon' => 'solar:book-linear',
            'group' => 'programs',
            'model' => \App\Models\StudentSubject::class,
            'permission' => 'subject',
            'field' => 'name',
            'status' => true,
        ],
        'nationalities' => [
            'label' => 'Nationalities',
            'icon' => 'solar:flag-linear',
            'group' => 'applicant_fields',
            'model' => \App\Models\Nationality::class,
            'permission' => 'nationality',
            'field' => 'name',
            'status' => true,
        ],
        'genders' => [
            'label' => 'Genders',
            'icon' => 'solar:user-linear',
            'group' => 'applicant_fields',
            'model' => \App\Models\Gender::class,
            'permission' => 'gender',
            'field' => 'name',
            'status' => true,
        ],
        'relationships' => [
            'label' => 'Relationships',
            'icon' => 'solar:link-linear',
            'group' => 'applicant_fields',
            'model' => \App\Models\RelationShip::class,
            'permission' => 'relation_ship',
            'field' => 'name',
            'status' => true,
        ],
        'languages' => [
            'label' => 'Languages',
            'icon' => 'solar:translation-linear',
            'group' => 'applicant_fields',
            'model' => \App\Models\StudentLanguage::class,
            'permission' => 'language',
            'field' => 'name',
            'status' => true,
        ],
        'payment_countries' => [
            'label' => 'Payment countries',
            'icon' => 'solar:global-linear',
            'group' => 'policies',
            'model' => \App\Models\PaymentCountry::class,
            'permission' => 'country',
            'field' => 'name',
            'status' => true,
        ],
        'enrollment_dates' => [
            'label' => 'Enrollment dates',
            'icon' => 'solar:calendar-linear',
            'group' => 'policies',
            'model' => \App\Models\AdmissionDate::class,
            'permission' => 'admission_date',
            'field' => 'date',
            'input' => 'date',
            'status' => true,
        ],
    ],

    'groups' => [
        'programs' => 'Programs',
        'applicant_fields' => 'Applicant fields',
        'policies' => 'Policies & dates',
    ],

];
